### PR TITLE
Release v0.5.0

### LINKED ISSUE #99: Service crash when a wan interface is brought up/down (regardless of log level)
**Script Version**
v0.4.3

**Describe the bug**

In support of discussion around multi interface support I've been testing current service behaviour when interfaces are brought up/down.

I've found that when a wan device interface is brought up or down it results in a crash due to the string.format() function encountering a nil as one of its inputs (the function doesn't support converting nils).

```
Something went wrong in the regulator thread
/usr/lib/sqm-autorate/sqm-autorate.lua:833: bad argument #2 to 'format' (string expected, got nil)
```

```
if rx_load and tx_load and up_del_stat and down_del_stat then
    logger(loglevel.DEBUG,
        string.format("%d,%d,%f,%f,%f,%f,%d,%d\n", lastchg_s, lastchg_ns, rx_load, tx_load,
        
            down_del_stat, up_del_stat, cur_dl_rate, cur_ul_rat
    -- output to log file before doing delta on the time
    csv_fd:write(string.format("%d,%d,%f,%f,%f,%f,%d,%d\n", lastchg_s, lastchg_ns, rx_load, tx_load,
        down_del_stat, up_del_stat, cur_dl_rate, cur_ul_rate))
else
    logger(loglevel.DEBUG,
        string.format(
            "Missing value error: rx_load = %s | tx_load = %s | down_del_stat = %s | up_del_stat = %s",
            rx_load, tx_load, down_del_stat, up_del_stat))
end
```

Amending line the string.format line to read as below avoids this error and the service can continue execution:

```
logger(loglevel.DEBUG,
    string.format(
        "Missing value error: rx_load = %s | tx_load = %s | down_del_stat = %s | up_del_stat = %s",
        tostring(rx_load), tostring(tx_load), tostring(down_del_stat), tostring(up_del_stat)))
```

**To Reproduce**
Whilst the service is running execute either the ifup or ifdown command, e.g. ```ifup wwan``` / ```ifdown wwan```

### LINKED ISSUE #131: [BUG] develop/main - crash due to unset SQMA_NO_STATISTICS environment variable
**Script Version**
v0.4.4 - develop/main post merge of #123 

**Describe the bug**

The service crashes when the no_statistics paremeter is not specified (either by config, cli arg or environment variable).

```
lua: ./sqma-settings.lua:356: bad argument #1 to 'lower' (string expected, got nil)
stack traceback:
	[C]: in function 'lower'
	./sqma-settings.lua:356: in function 'initialise'
	sqm-autorate.lua:115: in main chunk
	[C]: ?
```

This is because of the following section of code:

```
if not suppress_statistics then
    suppress_statistics = os.getenv("SQMA_NO_STATISTICS")
    suppress_statistics = suppress_statistics == "1" or
        string.lower(suppress_statistics) == "true" or
        string.lower(suppress_statistics) == "true" or
        string.lower(suppress_statistics) == "yes" or
        string.lower(suppress_statistics) == "y"
end
```

The string.lower() function cannot be passed a nil input (which occurs when the environment variable is not set).
This can be protected against by wrapping the os.getenv() function within tostring() as below:

```
suppress_statistics = tostring(os.getenv("SQMA_NO_STATISTICS"))
```

@chas-iot  should be a straightforward one to fix 🙂

### PR DESCRIPTION
**Pull request by chas-iot**
If you run _sqm-autorate_ via `service sqm-autorate enable && service sqm-autorate start` then nothing changes, skip to **Changes**. If you use an alternate method and it fails, then see **Starting _sqm-autorate_**

# Changes
- relicense all code to MPLv2
- reduced the output to /tmp to prevent using up all available space and then crashing
  - reduced the amount of logging
  - new option to stop recording statistics
    - /etc/config/sqm-autorate, section output, option suppress_statistics, set to 1, y, yes or true
- many, many bugfixes
- updated the documentation in README.md
- command line settings
  - depends on the lua argparse module
  - `lua sqm-autorate.lua -h` for help
  - `lua sqm-autorate.lua -s` to see the internal settings
- environment variable settings
- streamlined the setup script
- started modularisation of the lua code

# Starting _sqm-autorate_
_sqm-autorate_ is now split into several modules. This requires some changes to the way the program is started so that `lua` can find and load the modules.
* If you only use `service sqm-autorate start` etc. then no change.
* If you start by typing `lua /usr/lib/sqm-autorate/sqm-autorate.lua`, then try `cd /usr/lib/sqm-autorate/ ; lua sqm-autorate`.
* If you start by typing `/usr/lib/sqm-autorate/sqm-autorate.lua` then type `cd /usr/lib/sqm-autorate/ ; ./sqm-autorate.lua`
* Alternatively, adjust the `LUA_PATH` to add `/usr/lib/sqm-autorate/?.lua`

# Commits
## Fail-Safe
- Fix for GH issue #99 per @jeverley
- Closes Missing curl command when running setup Fail-Safe/sqm-autorate#93
- Removed bad reflectors.
- Per @jeverley's feedback, there is no need for a pattern match here.
- This appears to only be needed for ingress. Removing egress reference.
- Fixed incorrectly named variable.
- Attempt at br-lan fix.

## Daniel Lakeland
- add some lines and text to bandwidth diagram
- add an example run bw graph for use in readme

## Nils Andreas Svee
- set names on threads for debugging
- Add more reflectors in APAC region

## jeverley
- Incorporate changes discussed in #112 in clean rebase to develop/main

## Rich Brown
- Main lua code: Add csv_logger() function that observes the desired log level (to minimize logging long-term)
  - note: later superseded
- Update getstats.sh

## Chas-IOT
- version v0.5.0
- fixup .gitattributes for graphics
- fix use of argparse and align documentation (#133)
- re-organise setup script - incorporated most changes by @richb-hanover
- Fix #131 - crash when environment variable not set (#132)
- documentation updates
- fix formatting
- automate enable_verbose_baseline_output
- quieten statistics with new setting - uci: output.suppress_statistics - cli: --suppress-statistics - env: SQMA_SUPPRESS_STATISTICS
- quieten logging
- make setup and service ready for modularisation
- improved language and layout in julia/datavis.html (#72)
- Modularisation stage 2 - settings (#123)
- Modularisation stage 1 - requires and utilities (#122)
- prevent pollution from windows dev environment (#129)
- relicense all code to MPLv2 add contact details for developers
- edit and re-organise the README (#113)
- Fix download locations for move to new organisation
- revision of the docs to align with settings

### CODE REVIEW

**Review by Fail-Safe — APPROVED** [review]
Running for 13+ hours now without any runtime errors. I vote for "ship it!"

**Comment by richb-hanover** [comment]
@chas-iot , @Fail-Safe @Lochnair @jeverley 

I'm delighted that it's working for you. But you're one of the developers :-)

In #137, I'm advocating that we use as criteria:

- Install using the procedure available to a "member of the public"
- Run for 24 hours without surprises.

This minimizes confusion for forum testers who try out the new version. (It would be really confusing to announce 0.5.0, and then have to release 0.5.1 right away because of a silly typo...)

It's your call, but I'll get the new branch installed in the next couple hours and will report tomorrow morning, no matter what. Thanks.

**Comment by chas-iot** [comment]
@richb-hanover we are learning and one of the things that we need to achieve is to document how a 'm.o.p.' can install from one of our testing or development branches so that we can improve our processes. Hence my question to you in the discussion thread.

What I'm worried about for this release is less the functional running of the main _sqm-autorate.lua_ and more the installation and initial startup ( now there's a hostage to fortune 🤣 ).

The initial review with @Fail-Safe led to a significant change to the release notes to cover the various ways that _sqm-autorate_ can run.

**Comment by richb-hanover** [comment]
> What I'm worried about for this release is less the functional running of the main sqm-autorate.lua and more the installation and initial startup ( now there's a hostage to fortune 🤣 ).

OK. I believe it installs and runs OK.  Other comments:

- I think the install script should include a reminder to configure `/etc/config/sqm-autorate` (It's in the README, but nobody reads the README)

- Does the `... remove.sh` script both stop the `sqm-autorate` service and abort the running lua process(es)? That might explain why I had two copies of `sqm-autorate.lua` running earlier today. 

- Do the default settings avoid a problem with filling up `/tmp` with messages?

- I tried it on a router with no SQM installed. The error message was good:
```
root@FrontRoom-WNDR3800:~# sh setup.sh testing/next

This installation script cannot find an instance of the CAKE SQM running on any
network interface. 'sqm-autorate' currently works only with the CAKE SQM
Please install and configure CAKE before attempting to install sqm-autorate

After CAKE is installed and configured, its presence is detected by the
shell command 'tc qdisc | grep -i cake'

Exiting with no change
```

**Comment by chas-iot** [comment]
This release has had 24 hours of review, has run on at least 3 different routers, and at least 2 for more than 24 hours. While it is not perfect, I believe that it is an improvement.

**Pull request merged**
