### PR TITLE
Fix for GH issue #101 - prevents crash when a device is removed

### PR DESCRIPTION
**Pull request by jeverley**
Implements proposed fix for the issue raised in #101 and #105

### CODE REVIEW

**Comment by jeverley** [comment]
This PR now incorporates the following changes into the ratecontrol function:

- The service will no longer crash when a next_ul_rate / next_dl_rate is not set due to a skip of the rate control algorithm (stats files unreachable).
- The function will now attempt to re-open the rx and tx file descriptors when they cannot be read, this is required because when a device is re-added to the system the previous descriptors are no longer valid.
- The previous bytes and previous reading time values are reset when a device is re-added to the system.

**Comment by Lochnair** [comment]
This LGMT, but let me give it a run before merging to be sure

By the way, we generally use `develop/main` as a staging tree and only merge to `testing/lua-threads` when cutting a release.
Dunno if that branch should be renamed so it's actually clearer what its purpose is though

**Comment by jeverley** [comment]
> By the way, we generally use `develop/main` as a staging tree and only merge to `testing/lua-threads` when cutting a release. Dunno if that branch should be renamed so it's actually clearer what its purpose is though

Apologies will do that next time, I'd followed the pattern in https://github.com/sqm-autorate/sqm-autorate/pull/111.

**Comment by Lochnair** [comment]
No problem! We don't have any big changes queued up right now anyway I think, so you can probably just edit the PR to use the `develop/main` as the base branch and it should work without issues.

Generally if it's a small bug fix for something that actually affects people it'll go straight to `testing/lua-threads`, otherwise we'll let it sit in `develop/main` for a while until a few of us have been running the improvements there for a awhile so we don't publish something broken :)

**Comment by jeverley** [comment]
Will do a fresh PR to rebase on develop/main to make scope of change clearer.

**Pull request closed without merging**
