### PR TITLE
Scripted setup of /etc/config/sqm-autorate

### LINKED ISSUE #127: [FEATURE] Reconsider decision (not) to use /etc/config/sqm as a base
I am somewhat frustrated that (a while back) we decided not to use `/etc/config/sqm` as a base for the `sqm-autorate` settings. I would like to bring this up again, because doing this would be a real boon to adoption.

After installing and configuring SQM (via, say `luci-app-sqm`), there are good and useful values in its config file: both the proper interface, and the base settings. 

It's easy for a newcomer to set up SQM, then run the `setup.sh` script. If that script could snag the base values from the SQM config, they wouldn't have to do any editing.

And this would be a strong step toward a simple package (or an enhancement to the `luci-app-sqm` package) that "just works" for varying speed links.

**Describe the solution you'd like**
retrieve up & down speeds, and interface names from `/etc/config/sqm`

**Describe alternatives you've considered**
There was a previous discussion (on the forum?) about the difficulties in doing this. Perhaps these decisions could be re-considered for longer-term. Thanks.

### LINKED ISSUE #140: [FEATURE] What improvements could be made to the setup and remove scripts?
Let's use this to gather requirements for future versions of the setup and remove scripts

1. Ensure that by default, _sqm-autorate_ does not fill the router storage and crash. More changes required elsewhere to support this, however the setup script will play a part.
2. see if we can pull some information from `/etc/config/sqm` - this is not done at the moment because there may be more than 1 CAKE setup. - #127 
3. Ask some targetted questions regarding speeds and connection technologies to create a better initial `/etc/config/sqm-autorate`

Please add further suggestions?

### PR DESCRIPTION
**Pull request by chas-iot**
- Stops, starts and/or enables _sqm-autorate_ service
- watermarks `_VERSION` if not installed from `testing/lua-threads` to aid in testing
- new `/usr/lib/sqm-autorate/configure.sh` script that can be run many times
- called as part of `sqm-autorate-setup.sh`
- picks up previous settings from `/etc/config/sqm-autorate` if available
- attempts to detects the wan upload device and associated ifb4 or veth device if no previous settings available
- applies rules of thumb to calculate minimum speeds from the chosen 'maximum' speeds
- closes #140 
- closes #127 
- closes #146

### CODE REVIEW

**Comment by chas-iot** [comment]
The new sqm-autorate-configure.sh script is separate from and does not depend on setup script. To test  it, just download to the router and run - you may wish to make it executable after download.
- The script may be run multiple times, and may be safely interrupted with ctrl-c at any point before confirming the final list of settings. 
- No changes are made to the config file until after the list of settings is confirmed.
- The script does depend on a basic config file being present. 
- It does use the existing interfaces and maximum speeds settings from the config file.
- If there is no interface setup in the config file, the script will try to detect the primary wan as the upload and an associated ifb4 or veth interface. 
- The script will use rules of thumb to determine the minimum speed percentage
- It does optionally stop and restart the lua script after updating the settings

**Comment by richb-hanover** [comment]
I plan to spend some time on this today. Thanks for working on this.

**Comment by richb-hanover** [comment]
I had a couple errors right out of the chute. I came up with the following test procedure on my D-Link DIR-878 router that I've used with sqm-autorate before:

- run testing/lua-threads REMOVE.sh script; 
	cd /tmp
	curl https://raw.githubusercontent.com/sqm-autorate/sqm-autorate/develop/setup-config/sqm-autorate-remove.sh > remove.sh
- verify that all evidence is gone (Confirm: /tmp, /usr/lib, /etc/init.d have no sqm-autorate files)
- Ensure SQM is installed and configured (/etc/config/sqm has 30000/28000, cake, piece_of_cake)
- Run conf script

curl https://raw.githubusercontent.com/sqm-autorate/sqm-autorate/develop/setup-config/sqm-autorate-configure.sh > /tmp/sqm-autorate-configure.sh
sh sqm-autorate-configure.sh

Here's what happened:

1. I was asked two times for interfaces
2. several `uci commit` errors at the end

Here's the script:
```
root@D-Link-DIR-878:/tmp# sh sqm-autorate-configure.sh

>> Starting the 'sqm-autorate' configuration script.

You may interupt this script and re-run later. To re-run, at the router shell
prompt, type '/usr/lib/sqm-autorate/sqm-autorate-configure.sh'

Press return, or type y or yes if you want guided assistance to set up a ready
   to run configuration file for 'sqm-autorate' [Y/n]: y

This script does not reliably handle advanced or complex configurations of CAKE
You may be required to manually find and type the network device names

Here's the list of network devices known to CAKE:        <== Why am I asked twice?
wan
ifb4wan
unable to automatically detect the network upload device

These are the network devices known to CAKE        <== Why am I asked twice?
wan
ifb4wan

Please type in the upload network device name: ifb4wan
unable to automatically detect the network download device

These are the network devices known to CAKE
wan
ifb4wan

Please type in the download network device name: ^C

    SIGINT...       <== Aborted - re-ran


================================================================================

To re-run this configuration at any time, type the following command at the
router shell prompt: '/usr/lib/sqm-autorate/sqm-autorate-configure.sh'


root@D-Link-DIR-878:/tmp# sh sqm-autorate-configure.sh

>> Starting the 'sqm-autorate' configuration script.

You may interupt this script and re-run later. To re-run, at the router shell
prompt, type '/usr/lib/sqm-autorate/sqm-autorate-configure.sh'

Press return, or type y or yes if you want guided assistance to set up a ready
   to run configuration file for 'sqm-autorate' [Y/n]: y

This script does not reliably handle advanced or complex configurations of CAKE
You may be required to manually find and type the network device names

Here's the list of network devices known to CAKE:         <== Why am I asked twice?
wan
ifb4wan
unable to automatically detect the network upload device          <== Why am I asked twice?

These are the network devices known to CAKE
wan
ifb4wan

Please type in the upload network device name: wan

press return to accept detected network download device [ifb4wan]:

Please type in the maximum speed that you reasonably expect from your network
on a good day. This should be a little lower than the speed advertised by your
ISP, unless you have specific knowledge otherwise. The speed is measured in
kbits per second, where 1 mbit = 1000 kbits, and 1 gbit = 1000000 kbits.
The speed should be input with just digits and no punctuation

upload speed: 25000
download speed: 25000

The minimum tolerable speed is calculated from the speeds input above.
You may override the recommendation with care. The minimum must be lower than
the original speed. The input may be recalculated slightly, and in that case,
will be re-displayed for confirmation

upload minimum speed [5000]:
download minimum speed [5000]:

sqm-autorate logging uses storage on the router
Choose one of the following log levels
- FATAL     - minimal
- ERROR     - minimal
- WARN      - minimal, recommended
- INFO      - around 100 Kb per day, showing settings changes
- DEBUG     - for error finding, developers; use for short periods only
- TRACE     - for developers; use for short periods only

Type in one of the log levels, or press return to accept [WARN]:


sqm-autorate can output statistics that can be analysed with Julia scripts,
spreadsheets, or other statistical software.
The statistics use about 12 Mb of storage per day on the router

Type y or yes to choose to output the statistics [y/N]: y

Do you want to automatically start 'sqm-autorate' at reboot [Y/n]: y

Do you want to start 'sqm-autorate' now [Y/n]: y


================================================================================

Settings:

      UPLOAD DEVICE: wan
    DOWNLOAD DEVICE: ifb4wan

       UPLOAD SPEED: 25000
     UPLOAD PERCENT: 20
     UPLOAD MINIMUM: 5000

     DOWNLOAD SPEED: 25000
   DOWNLOAD PERCENT: 20
   DOWNLOAD MINIMUM: 5000

          LOG LEVEL: WARN
SUPPRESS STATISTICS: No

Start automatically: Yes
          Start now: Yes

Type y or yes to confirm the above input and continue;
  <ctrl-c> to interrupt and exit;  or
  anything else to start over [y/N]: y

restarting input

uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
sqm-autorate-configure.sh: line 441: service: not found
sqm-autorate-configure.sh: line 445: service: not found


================================================================================

To re-run this configuration at any time, type the following command at the
router shell prompt: '/usr/lib/sqm-autorate/sqm-autorate-configure.sh'

```

**Comment by richb-hanover** [comment]
PS - this script is very slick! Thanks.

**Comment by richb-hanover** [comment]
**Update:** There don't appear to be any `sqm-autorate` files in `/usr/lib`, `/tmp`, `/etc/config/` or `/etc/init.d`...

**Comment by chas-iot** [comment]
@richb-hanover The config script should does depend on sqm-autorate being installed. First time, it will run as the last step in setup. Then it may be re-run multiple times without removing sqm-autorate in the meantime.

If it is run without the installation and specifically, without the config file, you will see many of these errors.

**Comment by chas-iot** [comment]
> The config script does depend on sqm-autorate being installed

This does contradict what I wrote initially, apologies for the mis-steer. 

The config script does depend on the setup having been run. The config script may then be rerun multiple times without rerunning the setup.

two scenarios of interest
i) do a remove, clean install, and then the config script should automatically run as part of the setup. Does it detect the wan?
ii) after the above scenario, re-run the config script. Does it prompt with your previous network devices and (maximum) speeds?

Other questions. 
- When the setup is run (or the standalone config script) does it stop any running instance of sqm-autorate?
- Does the config script enable the service (if that question is answered y)?
- Does the config script start the service (if that question is answered y)?

**Comment by richb-hanover** [comment]
Ahah! So to keep it "all in the family" (or at least, in the same branch), I will first:

```
cd /tmp
wget https://raw.githubusercontent.com/sqm-autorate/sqm-autorate/develop/setup-config/sqm-autorate-setup.sh > sqm-autorate-setup.sh

sh ./sqm-autorate-setup.sh develop/setup-config # to retrieve this branch's setup script
```

Then retrieve and run the sqm-autorate.config.sh script, as described above. Right?

**Comment by richb-hanover** [comment]
One step forward... Now I get `404: Not Found` when attempting to execute the configure.sh script at the end of the setup.sh script. It appears that the contents of the configure.sh script are, in fact `404: Not Found`

```
root@D-Link-DIR-878:~# wget https://raw.githubusercontent.com/sqm-autorate/sqm-autorate/develop/setup-config/sqm-autorate-setup.s
h
Downloading 'https://raw.githubusercontent.com/sqm-autorate/sqm-autorate/develop/setup-config/sqm-autorate-setup.sh'
Connecting to 185.199.111.133:443
Writing to 'sqm-autorate-setup.sh'

root@D-Link-DIR-878:~# sh ./sqm-autorate-setup.sh develop/setup-config

Stopping 'sqm-autorate' (if installed)
>>> Refreshing package cache. This may take several minutes...
>>> Installing required packages via opkg...
>>> Installing required packages via luarocks...
Installing https://luarocks.org/vstruct-2.1.1-1.src.rock...
Using https://luarocks.org/vstruct-2.1.1-1.src.rock... switching to 'build' mode
Updating manifest for /usr/lib/luarocks/rocks
vstruct 2.1.1-1 is now built and installed in /usr

>>> Pulling down sqm-autorate operational files...
>>> Putting sqm-autorate lib files into place...
>>> Making sqm-autorate.lua, getstats.sh, and sqm-autorate-configure.sh executable...
>>> Putting config file into place...
>>> Putting service file into place...
> Installation complete, about to start configuration. You can enable and start the service by executing 'service sqm-autorate enable && service sqm-autorate start'.
/usr/lib/sqm-autorate/sqm-autorate-configure.sh: line 1: 404:: not found

root@D-Link-DIR-878:~# ll /usr/lib/sqm-autorate/
drwxr-xr-x    2 root     root             0 Feb 13 11:51 ./
drwxr-xr-x    1 root     root             0 Feb 13 11:51 ../
-rwxr-xr-x    1 root     root          3549 Feb 13 11:51 getstats.sh*
-rw-r--r--    1 root     root         11796 Feb 13 11:51 reflectors-icmp.csv
-rw-r--r--    1 root     root           401 Feb 13 11:51 reflectors-udp.csv
-rwxr-xr-x    1 root     root            14 Feb 13 11:51 sqm-autorate-configure.sh*
-rwxr-xr-x    1 root     root         45856 Feb 13 11:51 sqm-autorate.lua*
-rw-r--r--    1 root     root         16487 Feb 13 11:51 sqma-settings.lua
-rw-r--r--    1 root     root          4064 Feb 13 11:51 sqma-utilities.lua

root@D-Link-DIR-878:~# cat /usr/lib/sqm-autorate/sqm-autorate-configure.sh
404: Not Found
root@D-Link-DIR-878:~#
```

**Comment by chas-iot** [comment]
@richb-hanover please try again - fixed the 'minor' change that I didn't fully test

**Comment by richb-hanover** [comment]
Another step forward. `configure.sh` ran to completion, but service didn't start up.

Expand the Details below to see full output. Here's the interesting part of the output...

NB: `/etc/init.d/sqm-autorate` seems to contain a good service script, updated just now.

```
...
Type y or yes to confirm the above input and continue;
  <ctrl-c> to interrupt and exit;  or
  anything else to start over [y/N]: y

restarting input

/usr/lib/sqm-autorate/sqm-autorate-configure.sh: line 441: service: not found
/usr/lib/sqm-autorate/sqm-autorate-configure.sh: line 445: service: not found

root@D-Link-DIR-878:~# service list
...
/etc/init.d/sqm-autorate      	  disabled	   stopped

root@D-Link-DIR-878:~# service sqm-autorate enable
root@D-Link-DIR-878:~# service sqm-autorate start
root@D-Link-DIR-878:~# service list
...
/etc/init.d/sqm-autorate      	   enabled	   stopped

root@D-Link-DIR-878:~# service sqm-autorate start
root@D-Link-DIR-878:~# service list | grep auto
/etc/init.d/sqm-autorate      	   enabled	   stopped
root@D-Link-DIR-878:~# service sqm-autorate restart
root@D-Link-DIR-878:~# service list | grep auto
/etc/init.d/sqm-autorate      	   enabled	   stopped
```

<details>

```
root@D-Link-DIR-878:~# curl https://raw.githubusercontent.com/sqm-autorate/sqm-a
utorate/develop/setup-config/sqm-autorate-setup.sh > sqm-autorate-setup.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9972  100  9972    0     0  17909      0 --:--:-- --:--:-- --:--:-- 18032
root@D-Link-DIR-878:~# sh sqm-autorate-setup.sh develop/setup-config

Stopping 'sqm-autorate' (if installed)
>>> Refreshing package cache. This may take several minutes...
>>> Installing required packages via opkg...
>>> Installing required packages via luarocks...
Installing https://luarocks.org/vstruct-2.1.1-1.src.rock...
Using https://luarocks.org/vstruct-2.1.1-1.src.rock... switching to 'build' mode
Updating manifest for /usr/lib/luarocks/rocks
vstruct 2.1.1-1 is now built and installed in /usr

>>> Pulling down sqm-autorate operational files...
>>> Putting sqm-autorate lib files into place...
>>> Making sqm-autorate.lua, getstats.sh, and sqm-autorate-configure.sh executable...
>>> Putting config file into place...
>>> Putting service file into place...
> Installation complete, about to start configuration. You can enable and start the service by executing 'service sqm-autorate enable && service sqm-autorate start'.

>> Starting the 'sqm-autorate' configuration script.

You may interupt this script and re-run later. To re-run, at the router shell
prompt, type '/usr/lib/sqm-autorate/sqm-autorate-configure.sh'

Press return, or type y or yes if you want guided assistance to set up a ready
   to run configuration file for 'sqm-autorate' [Y/n]: y

This script does not reliably handle advanced or complex configurations of CAKE
You may be required to manually find and type the network device names

Here's the list of network devices known to CAKE:
wan
ifb4wan

press return to accept detected network upload device [wan]:

press return to accept detected network download device [ifb4wan]:

Please type in the maximum speed that you reasonably expect from your network
on a good day. This should be a little lower than the speed advertised by your
ISP, unless you have specific knowledge otherwise. The speed is measured in
kbits per second, where 1 mbit = 1000 kbits, and 1 gbit = 1000000 kbits.
The speed should be input with just digits and no punctuation

upload speed [10000]: 25000
download speed [10000]: 26000

The minimum tolerable speed is calculated from the speeds input above.
You may override the recommendation with care. The minimum must be lower than
the original speed. The input may be recalculated slightly, and in that case,
will be re-displayed for confirmation

upload minimum speed [5000]:
download minimum speed [5200]:

sqm-autorate logging uses storage on the router
Choose one of the following log levels
- FATAL     - minimal
- ERROR     - minimal
- WARN      - minimal, recommended
- INFO      - around 100 Kb per day, showing settings changes
- DEBUG     - for error finding, developers; use for short periods only
- TRACE     - for developers; use for short periods only

Type in one of the log levels, or press return to accept [WARN]:


sqm-autorate can output statistics that can be analysed with Julia scripts,
spreadsheets, or other statistical software.
The statistics use about 12 Mb of storage per day on the router

Type y or yes to choose to output the statistics [y/N]: y

Do you want to automatically start 'sqm-autorate' at reboot [Y/n]:

Do you want to start 'sqm-autorate' now [Y/n]:


================================================================================

Settings:

      UPLOAD DEVICE: wan
    DOWNLOAD DEVICE: ifb4wan

       UPLOAD SPEED: 25000
     UPLOAD PERCENT: 20
     UPLOAD MINIMUM: 5000

     DOWNLOAD SPEED: 26000
   DOWNLOAD PERCENT: 20
   DOWNLOAD MINIMUM: 5200

          LOG LEVEL: WARN
SUPPRESS STATISTICS: No

Start automatically: Yes
          Start now: Yes

Type y or yes to confirm the above input and continue;
  <ctrl-c> to interrupt and exit;  or
  anything else to start over [y/N]: y

restarting input

/usr/lib/sqm-autorate/sqm-autorate-configure.sh: line 441: service: not found
/usr/lib/sqm-autorate/sqm-autorate-configure.sh: line 445: service: not found


================================================================================

To re-run this configuration at any time, type the following command at the
router shell prompt: '/usr/lib/sqm-autorate/sqm-autorate-configure.sh'
```

</details>

**Comment by chas-iot** [comment]
@richb-hanover this should cover most issues reported

**Comment by richb-hanover** [comment]
The new script seemed to run OK and updates `/etc/config/sqm-autorate` as expected. Comments:

1. The version number doesn't appear in /tmp/sqm-autorate.log. It would be good to log that no matter what loglevel is selected. 
2. The `develop/setup-config` branch doesn't seem to affect CAKE settings. They don't change (or at least, don't change much) from the config'd minimums in `/etc/config/sqm-autorate`
3. After issuing `service sqm-autorate start`, `service | grep autorate` shows the service as enabled, but stopped
4. I still think there's something using a lot of CPU. This branch uses substantially all the CPU on ArcherC7, most of the CPU on D-Link DIR-878 (which I think has four cores...)

Thanks!

**Comment by chas-iot** [comment]
@richb-hanover thank-you for testing

>     1. The version number doesn't appear in /tmp/sqm-autorate.log. It would be good to log that no matter what loglevel is selected.
Please check in `/usr/lib/sqm-autorate/` - if there is no file named `sqm-autorate.lua-orig` then somehow the latest version of setup did not installed or run correctly. On my router, the log shows
```
Starting sqm-autorate.lua v0.5.0
        https://raw.githubusercontent.com/chas-iot/sqm-autorate/t
        Wed Feb 16 15:52:29 +08 2022
[INFO - 20220216T15:58:53]: next_ul_rate 660000 next_dl_rate 717291
```
If you followed your previous process of downloading the latest installation script then executing it with the parameter `develop/setup-config` then I would expect to see
```
Starting sqm-autorate.lua v0.5.0
        branch develop/setup-config
        Wed Feb 16 15:52:29 +08 2022
```

>     2. The `develop/setup-config` branch doesn't seem to affect CAKE settings. They don't change (or at least, don't change much) from the config'd minimums in `/etc/config/sqm-autorate`
This branch makes no change to the main operation, it's only about the initial installation and configuration. Therefore I believe this is unrelated

>     3. After issuing `service sqm-autorate start`, `service | grep autorate` shows the service as enabled, but stopped
That is consistent with previous behaviour. I think that we would need to add support in the service file to detect the status. @Fail-Safe started a rewrite to full `procd` support, so I don't plan to do anything about this for the moment

>     4. I still think there's something using a lot of CPU. This branch uses substantially all the CPU on ArcherC7, most of the CPU on D-Link DIR-878 (which I think has four cores...)
This PR / branch does not include the CPU bug fix from @Lochnair - so this is expected. We separately branched our respective changes off `develop/main` at similar times and neither branch is merged back yet

**Comment by richb-hanover** [comment]
Thanks. I guess I have some homework to double-check my work for tomorrow.

**Comment by chas-iot** [comment]
If you would like to test with both `develop/cpu-profiling` and `develop/setup-config`, try my throw-away branch that contains both.

```shell
cd /tmp
curl https://raw.githubusercontent.com/chas-iot/sqm-autorate/t/sqm-autorate-setup.sh > sqm-autorate-setup.sh

sh ./sqm-autorate-setup.sh chas-iot t
```

**Comment by chas-iot** [comment]
@richb-hanover thank-you again for the testing

> 2. I have not yet checked the CAKE-setting-modification tests.
Is this needed to close your review of the configuration script, or is it related to the CPU profiling?

To make sure you understand what is the `chas-iot` branch `t`. It's a throwaway that I created so as to merge and run the latest and greatest `cpu-profiling`, `setup-config` and the still draft `plugin` changes. I have been running this on my router for the past 30 hours.
- The `setup-config` changes barely touch the `sqm-autorate.lua` script: minimal changes to the logging level of some messages to DEBUG; and, at install time, the contents of the _VERSION
- The `cpu-profiling` branch re-organises some code in the baseline calculator (thread) so as to reduce CPU usage
- The `plugin` changes adds some hooks in the rate control thread but should not actually change the operation (unless a plugin is loaded).

**Comment by richb-hanover** [comment]
Yes, let's close this config script test thread. It's definitely better than previously, and is unrelated to the high-CPU issues that document my observations. Thanks.

**Comment by richb-hanover** [comment]
I won't have time to look at this 'til next week. If you're happy, it looks good to me.

**Pull request merged**
